# Generated by Django 5.1.15 on 2026-10-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstatusoverride_new_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=50),
        ),
    ]
