# Generated by Django 5.1.15 on 2026-10-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitydocument',
            name='file_reference',
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='document_data',
            field=models.BinaryField(editable=False),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='has_profile_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='name_on_document',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='identitydocument',
            index=models.Index(fields=['id_number'], name='idx_identity_doc_id_number'),
        ),
        migrations.AddConstraint(
            model_name='identitydocument',
            constraint=models.CheckConstraint(condition=models.Q(('consent_given', False), ('consented_at__isnull', False), _connector='OR'), name='identity_document_consent_has_timestamp'),
        ),
    ]
