# Generated by Django 5.1.15 on 2026-10-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_value', models.CharField(max_length=6)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auth Code',
                'verbose_name_plural': 'Auth Codes',
                'db_table': 'auth_codes',
            },
        ),
        migrations.CreateModel(
            name='AuthCodeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_successful', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auth Code Attempt',
                'verbose_name_plural': 'Auth Code Attempts',
                'db_table': 'auth_code_attempts',
            },
        ),
        migrations.CreateModel(
            name='AuthCodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Auth Code Status',
                'verbose_name_plural': 'Auth Code Statuses',
                'db_table': 'auth_code_statuses',
            },
        ),
        migrations.CreateModel(
            name='AuthCodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Auth Code Type',
                'verbose_name_plural': 'Auth Code Types',
                'db_table': 'auth_code_types',
            },
        ),
    ]
