# Generated by Django 5.1.15 on 2026-10-01 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authcodeattempt',
            name='attempted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auth_code_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authcodeattempt',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='codes.authcode'),
        ),
        migrations.AddField(
            model_name='authcode',
            name='auth_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='codes.authcodestatus'),
        ),
        migrations.AddField(
            model_name='authcode',
            name='code_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='codes.authcodetype'),
        ),
    ]
