# Generated by Django 5.1.15 on 2026-10-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminaccesslog',
            options={'ordering': ['-accessed_at'], 'verbose_name': 'Admin Access Log', 'verbose_name_plural': 'Admin Access Logs'},
        ),
        migrations.AddField(
            model_name='adminaccesslog',
            name='action',
            field=models.CharField(default='view', help_text='What the administrator did: view, download, review, contact_release.', max_length=30),
        ),
        migrations.AddField(
            model_name='adminaccesslog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the administrator at the time of access.', null=True),
        ),
    ]
