# Generated by Django 5.1.15 on 2026-10-01 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0004_initial'),
        ('listings', '0002_initial'),
        ('reports', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='target_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.listingreportcategory'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_message_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='target_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.message'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.messagereportcategory'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='target_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.reviewreportcategory'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_user_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.userreportcategory'),
        ),
    ]
